application: unlimitedimagecombiner
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: UIC/stylesheets
  
- url: /javascripts
  static_dir: UIC/javascripts
  
- url: /.*
  script: _go_app